// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: kvmessages/messages.proto

package kvmessages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_PING          MessageType = 0
	MessageType_PING_RESPONSE MessageType = 1
	MessageType_KEY_VALUE     MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "PING",
		1: "PING_RESPONSE",
		2: "KEY_VALUE",
	}
	MessageType_value = map[string]int32{
		"PING":          0,
		"PING_RESPONSE": 1,
		"KEY_VALUE":     2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_kvmessages_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_kvmessages_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_kvmessages_messages_proto_rawDescGZIP(), []int{0}
}

// The request message containing the user's name.
type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hello int32 `protobuf:"varint,1,opt,name=hello,proto3" json:"hello,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvmessages_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kvmessages_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_kvmessages_messages_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetHello() int32 {
	if x != nil {
		return x.Hello
	}
	return 0
}

// The response message containing the greetings
type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hello int32 `protobuf:"varint,1,opt,name=hello,proto3" json:"hello,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvmessages_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kvmessages_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_kvmessages_messages_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetHello() int32 {
	if x != nil {
		return x.Hello
	}
	return 0
}

type KeyValueMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KeyValueMessage) Reset() {
	*x = KeyValueMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvmessages_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueMessage) ProtoMessage() {}

func (x *KeyValueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kvmessages_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueMessage.ProtoReflect.Descriptor instead.
func (*KeyValueMessage) Descriptor() ([]byte, []int) {
	return file_kvmessages_messages_proto_rawDescGZIP(), []int{2}
}

func (x *KeyValueMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValueMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=kvmessages.MessageType" json:"type,omitempty"`
	// Types that are assignable to Content:
	//
	//	*ServerMessage_Ping
	//	*ServerMessage_PingResponse
	//	*ServerMessage_KeyValue
	Content isServerMessage_Content `protobuf_oneof:"content"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kvmessages_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kvmessages_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_kvmessages_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ServerMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_PING
}

func (m *ServerMessage) GetContent() isServerMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *ServerMessage) GetPing() *PingRequest {
	if x, ok := x.GetContent().(*ServerMessage_Ping); ok {
		return x.Ping
	}
	return nil
}

func (x *ServerMessage) GetPingResponse() *PingResponse {
	if x, ok := x.GetContent().(*ServerMessage_PingResponse); ok {
		return x.PingResponse
	}
	return nil
}

func (x *ServerMessage) GetKeyValue() *KeyValueMessage {
	if x, ok := x.GetContent().(*ServerMessage_KeyValue); ok {
		return x.KeyValue
	}
	return nil
}

type isServerMessage_Content interface {
	isServerMessage_Content()
}

type ServerMessage_Ping struct {
	Ping *PingRequest `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

type ServerMessage_PingResponse struct {
	PingResponse *PingResponse `protobuf:"bytes,3,opt,name=ping_response,json=pingResponse,proto3,oneof"`
}

type ServerMessage_KeyValue struct {
	KeyValue *KeyValueMessage `protobuf:"bytes,4,opt,name=key_value,json=keyValue,proto3,oneof"`
}

func (*ServerMessage_Ping) isServerMessage_Content() {}

func (*ServerMessage_PingResponse) isServerMessage_Content() {}

func (*ServerMessage_KeyValue) isServerMessage_Content() {}

var File_kvmessages_messages_proto protoreflect.FileDescriptor

var file_kvmessages_messages_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6b, 0x76, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6b, 0x76, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x22, 0x24, 0x0a, 0x0c,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x22, 0x39, 0x0a, 0x0f, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xf3, 0x01,
	0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e,
	0x6b, 0x76, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x04,
	0x70, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6b, 0x76, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x3f, 0x0a, 0x0d, 0x70,
	0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6b, 0x76, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0c,
	0x70, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09,
	0x6b, 0x65, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6b, 0x76, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x4b, 0x65, 0x79,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x08,
	0x6b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x2a, 0x39, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d,
	0x50, 0x49, 0x4e, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x01, 0x12,
	0x0d, 0x0a, 0x09, 0x4b, 0x45, 0x59, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x02, 0x32, 0x92,
	0x01, 0x0a, 0x08, 0x4b, 0x56, 0x53, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x04, 0x70,
	0x69, 0x6e, 0x67, 0x12, 0x17, 0x2e, 0x6b, 0x76, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6b,
	0x76, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d,
	0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x6b, 0x76, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x19, 0x2e, 0x6b, 0x76, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6b, 0x76, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x6b, 0x76, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kvmessages_messages_proto_rawDescOnce sync.Once
	file_kvmessages_messages_proto_rawDescData = file_kvmessages_messages_proto_rawDesc
)

func file_kvmessages_messages_proto_rawDescGZIP() []byte {
	file_kvmessages_messages_proto_rawDescOnce.Do(func() {
		file_kvmessages_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_kvmessages_messages_proto_rawDescData)
	})
	return file_kvmessages_messages_proto_rawDescData
}

var file_kvmessages_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kvmessages_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kvmessages_messages_proto_goTypes = []any{
	(MessageType)(0),        // 0: kvmessages.MessageType
	(*PingRequest)(nil),     // 1: kvmessages.PingRequest
	(*PingResponse)(nil),    // 2: kvmessages.PingResponse
	(*KeyValueMessage)(nil), // 3: kvmessages.KeyValueMessage
	(*ServerMessage)(nil),   // 4: kvmessages.ServerMessage
}
var file_kvmessages_messages_proto_depIdxs = []int32{
	0, // 0: kvmessages.ServerMessage.type:type_name -> kvmessages.MessageType
	1, // 1: kvmessages.ServerMessage.ping:type_name -> kvmessages.PingRequest
	2, // 2: kvmessages.ServerMessage.ping_response:type_name -> kvmessages.PingResponse
	3, // 3: kvmessages.ServerMessage.key_value:type_name -> kvmessages.KeyValueMessage
	1, // 4: kvmessages.KVSevice.ping:input_type -> kvmessages.PingRequest
	4, // 5: kvmessages.KVSevice.Communicate:input_type -> kvmessages.ServerMessage
	2, // 6: kvmessages.KVSevice.ping:output_type -> kvmessages.PingResponse
	4, // 7: kvmessages.KVSevice.Communicate:output_type -> kvmessages.ServerMessage
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_kvmessages_messages_proto_init() }
func file_kvmessages_messages_proto_init() {
	if File_kvmessages_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kvmessages_messages_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvmessages_messages_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvmessages_messages_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*KeyValueMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kvmessages_messages_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_kvmessages_messages_proto_msgTypes[3].OneofWrappers = []any{
		(*ServerMessage_Ping)(nil),
		(*ServerMessage_PingResponse)(nil),
		(*ServerMessage_KeyValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kvmessages_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvmessages_messages_proto_goTypes,
		DependencyIndexes: file_kvmessages_messages_proto_depIdxs,
		EnumInfos:         file_kvmessages_messages_proto_enumTypes,
		MessageInfos:      file_kvmessages_messages_proto_msgTypes,
	}.Build()
	File_kvmessages_messages_proto = out.File
	file_kvmessages_messages_proto_rawDesc = nil
	file_kvmessages_messages_proto_goTypes = nil
	file_kvmessages_messages_proto_depIdxs = nil
}
