// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: kvmessages/messages.proto

package kvmessages

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KVSevice_Ping_FullMethodName = "/kvmessages.KVSevice/ping"
)

// KVSeviceClient is the client API for KVSevice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type KVSeviceClient interface {
	// Sends a greeting
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type kVSeviceClient struct {
	cc grpc.ClientConnInterface
}

func NewKVSeviceClient(cc grpc.ClientConnInterface) KVSeviceClient {
	return &kVSeviceClient{cc}
}

func (c *kVSeviceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, KVSevice_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVSeviceServer is the server API for KVSevice service.
// All implementations must embed UnimplementedKVSeviceServer
// for forward compatibility.
//
// The greeting service definition.
type KVSeviceServer interface {
	// Sends a greeting
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedKVSeviceServer()
}

// UnimplementedKVSeviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKVSeviceServer struct{}

func (UnimplementedKVSeviceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedKVSeviceServer) mustEmbedUnimplementedKVSeviceServer() {}
func (UnimplementedKVSeviceServer) testEmbeddedByValue()                  {}

// UnsafeKVSeviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KVSeviceServer will
// result in compilation errors.
type UnsafeKVSeviceServer interface {
	mustEmbedUnimplementedKVSeviceServer()
}

func RegisterKVSeviceServer(s grpc.ServiceRegistrar, srv KVSeviceServer) {
	// If the following call pancis, it indicates UnimplementedKVSeviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KVSevice_ServiceDesc, srv)
}

func _KVSevice_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVSeviceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KVSevice_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVSeviceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KVSevice_ServiceDesc is the grpc.ServiceDesc for KVSevice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KVSevice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvmessages.KVSevice",
	HandlerType: (*KVSeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ping",
			Handler:    _KVSevice_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kvmessages/messages.proto",
}
